name: khair_ul_madaaris_library
description: "Premium Library Management System for Khair-ul-Madaaris"
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Google Services
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  # HTTP
  http: ^1.2.2

  # QR Code Scanning
  mobile_scanner: ^5.2.3

  # Storage
  shared_preferences: ^2.3.3

  # Animations
  flutter_animate: ^4.5.2

  # UI/UX
  flutter_svg: ^2.0.16

  # Responsive Design
  flutter_screenutil: ^5.9.3

  # Note: If build fails, try latest version
  # flutter_screenutil: ^5.10.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.2

  # Charts
  fl_chart: ^0.70.0

  # Logging
  logger: ^2.5.0

  # Vibration/Haptics
  vibration: ^3.1.4

  # Network Connectivity
  connectivity_plus: ^6.1.2

  # App Updates (In-App Update System)
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#2C5265"

# Splash Screen Configuration
flutter_native_splash:
  color: "#2C5265"
  image: assets/images/splash_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
